export const lightTheme = {
    colors: {
      primary: '#24292f',
      secondary: '#ffffff',
      accent: '#0969da',
      background: '#f6f8fa',
      sidebarBackground: '#ffffff',
      logoColor: '#24292f',
      navLabelColor: '#24292f',
      navIconColor: '#57606a',
      navLabelActiveColor: '#0969da',
      navIconActiveColor: '#0969da', 
      navLabelHoverColor: '#24292f',
      navIconHoverColor: '#24292f',
      navLinkActiveColor: '#0969da',
      navLinkActiveColorBackground: '#f6f8fa',
      navItemHoverColorBackground: '#f6f8fa',
      headerBackground: '#ffffff',
      listItemHoverBackground: '#f6f8fa',
      buttonHeaderBgColor: '#2da44e',
      buttonHeaderColor: '#ffffff',
      tabBackground: '#ffffff',
      contentBackground: '#ffffff',
      contentColor: '#24292f',
      contentHeaderColor: '#24292f',
      contentHeaderBackground: '#ffffff',
      contentToolbarBackground: '#ffffff',  
      contentToolbarColor: '#24292f',
      footerBackground: '#ffffff',
      boxShadowColor: '#d0d7de',
      linkColor: '#0969da',
      linkHoverColor: '#0969da',
      linkActiveColor: '#0969da',
      linkBackground: '#ffffff',
      tabColor: '#24292f',
      tabActiveColor: '#0969da',
      tabHoverColor: '#0969da',
      searchColor: '#24292f',
      searchBackground: '#f6f8fa',
      modalBackground: '#ffffff',
      modalColor: '#24292f',
      modalHeaderColor: '#24292f',
      modalOverlayColor: 'rgba(0, 0, 0, 0.5)',
    },
    scrollbar: {
      thumbColor: '#d0d7de',
      trackColor: '#f6f8fa',
      thumbHoverColor: '#8b949e'
    }
  };
  export default lightTheme;