export const radioStations = [
  { name: "Вести FM", url: "http://icecast-vgtrk.cdnvideo.ru/vestifm_dontr", disabled: false },
  { name: "Наше радио", url: "https://nashe1.hostingradio.ru/nashe-128.mp3", disabled: false },
  { name: "Rock", url: "https://radiorecord.hostingradio.ru/rock96.aacp", disabled: false },
  { name: "10's Dance", url: "https://radiorecord.hostingradio.ru/201096.aacp", disabled: false },
  { name: "2-step", url: "https://radiorecord.hostingradio.ru/2step96.aacp", disabled: false },
  { name: "60's Dance", url: "https://radiorecord.hostingradio.ru/cadillac96.aacp", disabled: false },
  { name: "70's Dance", url: "https://radiorecord.hostingradio.ru/197096.aacp", disabled: false },
  { name: "A State of Trance", url: "https://radiorecord.hostingradio.ru/asot96.aacp", disabled: false },
  { name: "Afro House", url: "https://radiorecord.hostingradio.ru/afro96.aacp", disabled: false },
  { name: "Ambient", url: "https://radiorecord.hostingradio.ru/ambient96.aacp", disabled: false },
  { name: "Armin van Buuren", url: "https://radiorecord.hostingradio.ru/armin96.aacp", disabled: false },
  { name: "Bass House", url: "https://radiorecord.hostingradio.ru/jackin96.aacp", disabled: false },
  { name: "Beach Party", url: "https://radiorecord.hostingradio.ru/beach96.aacp", disabled: false },
  { name: "Big Hits", url: "https://radiorecord.hostingradio.ru/bighits96.aacp", disabled: false },
  { name: "Black Rap", url: "https://radiorecord.hostingradio.ru/yo96.aacp", disabled: false },
  { name: "Breaks", url: "https://radiorecord.hostingradio.ru/brks96.aacp", disabled: false },
  { name: "Chill House", url: "https://radiorecord.hostingradio.ru/chillhouse96.aacp", disabled: false },
  { name: "Chill-Out", url: "https://radiorecord.hostingradio.ru/chil96.aacp", disabled: false },
  { name: "Christmas", url: "https://radiorecord.hostingradio.ru/christmas96.aacp", disabled: false },
  { name: "Christmas Chill", url: "https://radiorecord.hostingradio.ru/christmaschill96.aacp", disabled: false },
  { name: "Complextro", url: "https://radiorecord.hostingradio.ru/complextro96.aacp", disabled: false },
  { name: "D'n'B Classics", url: "https://radiorecord.hostingradio.ru/drumhits96.aacp", disabled: false },
  { name: "Dancecore", url: "https://radiorecord.hostingradio.ru/dc96.aacp", disabled: false },
  { name: "Darkside", url: "https://radiorecord.hostingradio.ru/darkside96.aacp", disabled: false },
  { name: "David Guetta", url: "https://radiorecord.hostingradio.ru/guetta96.aacp", disabled: false },
  { name: "Deep", url: "https://radiorecord.hostingradio.ru/deep96.aacp", disabled: false },
  { name: "Disco/Funk", url: "https://radiorecord.hostingradio.ru/discofunk96.aacp", disabled: false },
  { name: "DJ Gvozd", url: "https://radiorecord.hostingradio.ru/djgvozd96.aacp", disabled: false },
  { name: "DJ Цветкоff", url: "https://radiorecord.hostingradio.ru/tsvetkov96.aacp", disabled: false },
  { name: "Dream Dance", url: "https://radiorecord.hostingradio.ru/dream96.aacp", disabled: false },
  { name: "Dream Pop", url: "https://radiorecord.hostingradio.ru/dreampop96.aacp", disabled: false },
  { name: "Dubstep", url: "https://radiorecord.hostingradio.ru/dub96.aacp", disabled: false },
  { name: "EDM", url: "https://radiorecord.hostingradio.ru/club96.aacp", disabled: false },
  { name: "EDM Classics", url: "https://radiorecord.hostingradio.ru/edmhits96.aacp", disabled: false },
  { name: "Electro", url: "https://radiorecord.hostingradio.ru/elect96.aacp", disabled: false },
  { name: "Eurodance", url: "https://radiorecord.hostingradio.ru/eurodance96.aacp", disabled: false },
  { name: "Feel", url: "https://radiorecord.hostingradio.ru/feel96.aacp", disabled: false },
  { name: "Festivals", url: "https://radiorecord.hostingradio.ru/livedjsets96.aacp", disabled: false },
  { name: "Future Bass", url: "https://radiorecord.hostingradio.ru/fbass96.aacp", disabled: false },
  { name: "Future House", url: "https://radiorecord.hostingradio.ru/fut96.aacp", disabled: false },
  { name: "Future Rave", url: "https://radiorecord.hostingradio.ru/futurerave96.aacp", disabled: false },
  { name: "GOA/PSY", url: "https://radiorecord.hostingradio.ru/goa96.aacp", disabled: false },
  { name: "Groove/Tribal", url: "https://radiorecord.hostingradio.ru/groovetribal96.aacp", disabled: false },
  { name: "Hard Bass", url: "https://radiorecord.hostingradio.ru/hbass96.aacp", disabled: false },
  { name: "Hardstyle", url: "https://radiorecord.hostingradio.ru/teo96.aacp", disabled: false },
  { name: "House Classics", url: "https://radiorecord.hostingradio.ru/houseclss96.aacp", disabled: false },
  { name: "House Hits", url: "https://radiorecord.hostingradio.ru/househits96.aacp", disabled: false },
  { name: "Hypnotic", url: "https://radiorecord.hostingradio.ru/hypno96.aacp", disabled: false },
  { name: "Innocence", url: "https://radiorecord.hostingradio.ru/ibiza96.aacp", disabled: false },
  { name: "Jungle", url: "https://radiorecord.hostingradio.ru/jungle96.aacp", disabled: false },
  { name: "Lady Waks", url: "https://radiorecord.hostingradio.ru/ladywaks96.aacp", disabled: false },
  { name: "Latina Dance", url: "https://radiorecord.hostingradio.ru/latina96.aacp", disabled: false },
  { name: "Liquid Funk", url: "https://radiorecord.hostingradio.ru/liquidfunk96.aacp", disabled: false },
  { name: "Lo-Fi", url: "https://radiorecord.hostingradio.ru/lofi96.aacp", disabled: false },
  { name: "Lo-Fi House", url: "https://radiorecord.hostingradio.ru/lofihouse96.aacp", disabled: false },
  { name: "Martin Garrix", url: "https://radiorecord.hostingradio.ru/martingarrix96.aacp", disabled: false },
  { name: "Megamix", url: "https://radiorecord.hostingradio.ru/mix96.aacp", disabled: false },
  { name: "Midtempo", url: "https://radiorecord.hostingradio.ru/mt96.aacp", disabled: false },
  { name: "Minimal/Tech", url: "https://radiorecord.hostingradio.ru/mini96.aacp", disabled: false },
  { name: "Moombahton", url: "https://radiorecord.hostingradio.ru/mmbt96.aacp", disabled: false },
  { name: "Nejtrino & Baur", url: "https://radiorecord.hostingradio.ru/nejtrinobaur96.aacp", disabled: false },
  { name: "Neurofunk", url: "https://radiorecord.hostingradio.ru/neurofunk96.aacp", disabled: false },
  { name: "Nu Dance", url: "https://radiorecord.hostingradio.ru/nudance96.aacp", disabled: false },
  { name: "Oliver Heldens", url: "https://radiorecord.hostingradio.ru/oliverheldens96.aacp", disabled: false },
  { name: "Organic", url: "https://radiorecord.hostingradio.ru/organic96.aacp", disabled: false },
  { name: "Party 24/7", url: "https://radiorecord.hostingradio.ru/party96.aacp", disabled: false },
  { name: "Phonk", url: "https://radiorecord.hostingradio.ru/phonk96.aacp", disabled: false },
  { name: "Pirate Station", url: "https://radiorecord.hostingradio.ru/ps96.aacp", disabled: false },
  { name: "Progressive", url: "https://radiorecord.hostingradio.ru/progr96.aacp", disabled: false },
  { name: "Rap Hits", url: "https://radiorecord.hostingradio.ru/rap96.aacp", disabled: false },
  { name: "Rave FM", url: "https://radiorecord.hostingradio.ru/rave96.aacp", disabled: false },
  { name: "Rave FM", url: "https://radiorecord.hostingradio.ru/rave96.aacp", disabled: false },
  { name: "Record", url: "https://radiorecord.hostingradio.ru/rr_main96.aacp", disabled: false },
  { name: "Record 80-х", url: "https://radiorecord.hostingradio.ru/198096.aacp", disabled: false },
  { name: "Record Classix", url: "https://radiorecord.hostingradio.ru/classix96.aacp", disabled: false },
  { name: "Record Club Show", url: "https://radiorecord.hostingradio.ru/clubshow96.aacp", disabled: false },
  { name: "Record Gold", url: "https://radiorecord.hostingradio.ru/gold96.aacp", disabled: false },
  { name: "Reggae", url: "https://radiorecord.hostingradio.ru/reggae32.aacp", disabled: false },
  { name: "Remix", url: "https://radiorecord.hostingradio.ru/rmx96.aacp", disabled: false },
  { name: "Russian Gold", url: "https://radiorecord.hostingradio.ru/russiangold96.aacp", disabled: false },
  { name: "Russian Hits", url: "https://radiorecord.hostingradio.ru/russianhits96.aacp", disabled: false },
  { name: "Russian Mix", url: "https://radiorecord.hostingradio.ru/rus96.aacp", disabled: false },
  { name: "Summer Dance", url: "https://radiorecord.hostingradio.ru/summerparty96.aacp", disabled: false },
  { name: "Summer Lounge", url: "https://radiorecord.hostingradio.ru/summerlounge96.aacp", disabled: false },
  { name: "Synthwave", url: "https://radiorecord.hostingradio.ru/synth96.aacp", disabled: false },
  { name: "Tech House", url: "https://radiorecord.hostingradio.ru/techouse96.aacp", disabled: false },
  { name: "Techno", url: "https://radiorecord.hostingradio.ru/techno96.aacp", disabled: false },
  { name: "Technopop", url: "https://radiorecord.hostingradio.ru/technopop96.aacp", disabled: false },
  { name: "Tecktonik", url: "https://radiorecord.hostingradio.ru/tecktonik96.aacp", disabled: false },
  { name: "Tiesto", url: "https://radiorecord.hostingradio.ru/tiesto96.aacp", disabled: false },
  { name: "TOP 100 EDM", url: "https://radiorecord.hostingradio.ru/top100edm96.aacp", disabled: false },
  { name: "Trance Classics", url: "https://radiorecord.hostingradio.ru/trancehits96.aacp", disabled: false },
  { name: "Trancehouse", url: "https://radiorecord.hostingradio.ru/trancehouse96.aacp", disabled: false },
  { name: "Trancemission", url: "https://radiorecord.hostingradio.ru/tm96.aacp", disabled: false },
  { name: "Trap", url: "https://radiorecord.hostingradio.ru/trap96.aacp", disabled: false },
  { name: "Tropical", url: "https://radiorecord.hostingradio.ru/trop96.aacp", disabled: false },
  { name: "UK Garage", url: "https://radiorecord.hostingradio.ru/ukgarage96.aacp", disabled: false },
  { name: "Ultra Music Festival", url: "https://radiorecord.hostingradio.ru/ultra96.aacp", disabled: false },
  { name: "Uplifting", url: "https://radiorecord.hostingradio.ru/uplift96.aacp", disabled: false },
  { name: "VIP House", url: "https://radiorecord.hostingradio.ru/vip96.aacp", disabled: false },
  { name: "Workout", url: "https://radiorecord.hostingradio.ru/workout32.aacp", disabled: false },
  { name: "Веснушка FM", url: "https://radiorecord.hostingradio.ru/deti96.aacp", disabled: false }, 
  { name: "Гастарбайтер FM", url: "https://radiorecord.hostingradio.ru/gast96.aacp", disabled: false },
  { name: "Гоп FM", url: "https://radiorecord.hostingradio.ru/gop96.aacp", disabled: false },
  { name: "Колбасный Цех", url: "https://radiorecord.hostingradio.ru/pump96.aacp", disabled: false },
  { name: "Маятник Фуко", url: "https://radiorecord.hostingradio.ru/mf96.aacp", disabled: false },
  { name: "Медляк FM", url: "https://radiorecord.hostingradio.ru/mdl96.aacp", disabled: false },
  { name: "На Хайпе", url: "https://radiorecord.hostingradio.ru/hype96.aacp", disabled: false },
  { name: "На шашлыки!", url: "https://radiorecord.hostingradio.ru/nashashlyki96.aacp", disabled: false },
  { name: "Нафталин FM", url: "https://radiorecord.hostingradio.ru/naft96.aacp", disabled: false },
  { name: "Рекорд 00-х", url: "https://radiorecord.hostingradio.ru/200096.aacp", disabled: false },
  { name: "Руки Вверх!", url: "https://radiorecord.hostingradio.ru/rv96.aacp", disabled: false },
  { name: "Русская Зима", url: "https://radiorecord.hostingradio.ru/ruszima96.aacp", disabled: false },
  { name: "Симфония FM", url: "https://radiorecord.hostingradio.ru/symph96.aacp", disabled: false },
  { name: "Сказки MC V", url: "https://radiorecord.hostingradio.ru/skazki96.aacp", disabled: false },
  { name: "Супердискотека 90-х", url: "https://radiorecord.hostingradio.ru/sd9096.aacp", disabled: false },
  ];