export const radioStations = [
  { name: "Rock", url: "https://radiorecord.hostingradio.ru/rock96.aacp" },
  { name: "10's Dance", url: "https://radiorecord.hostingradio.ru/201096.aacp" },
  { name: "2-step", url: "https://radiorecord.hostingradio.ru/2step96.aacp" },
  { name: "60's Dance", url: "https://radiorecord.hostingradio.ru/cadillac96.aacp" },
  { name: "70's Dance", url: "https://radiorecord.hostingradio.ru/197096.aacp" },
  { name: "A State of Trance", url: "https://radiorecord.hostingradio.ru/asot96.aacp" },
  { name: "Afro House", url: "https://radiorecord.hostingradio.ru/afro96.aacp" },
  { name: "Ambient", url: "https://radiorecord.hostingradio.ru/ambient96.aacp" },
  { name: "Armin van Buuren", url: "https://radiorecord.hostingradio.ru/armin96.aacp" },
  { name: "Bass House", url: "https://radiorecord.hostingradio.ru/jackin96.aacp" },
  { name: "Beach Party", url: "https://radiorecord.hostingradio.ru/beach96.aacp" },
  { name: "Big Hits", url: "https://radiorecord.hostingradio.ru/bighits96.aacp" },
  { name: "Black Rap", url: "https://radiorecord.hostingradio.ru/yo96.aacp" },
  { name: "Breaks", url: "https://radiorecord.hostingradio.ru/brks96.aacp" },
  { name: "Chill House", url: "https://radiorecord.hostingradio.ru/chillhouse96.aacp" },
  { name: "Chill-Out", url: "https://radiorecord.hostingradio.ru/chil96.aacp" },
  { name: "Christmas", url: "https://radiorecord.hostingradio.ru/christmas96.aacp" },
  { name: "Christmas Chill", url: "https://radiorecord.hostingradio.ru/christmaschill96.aacp" },
  { name: "Complextro", url: "https://radiorecord.hostingradio.ru/complextro96.aacp" },
  { name: "D'n'B Classics", url: "https://radiorecord.hostingradio.ru/drumhits96.aacp" },
  { name: "Dancecore", url: "https://radiorecord.hostingradio.ru/dc96.aacp" },
  { name: "Darkside", url: "https://radiorecord.hostingradio.ru/darkside96.aacp" },
  { name: "David Guetta", url: "https://radiorecord.hostingradio.ru/guetta96.aacp" },
  { name: "Deep", url: "https://radiorecord.hostingradio.ru/deep96.aacp" },
  { name: "Disco/Funk", url: "https://radiorecord.hostingradio.ru/discofunk96.aacp" },
  { name: "DJ Gvozd", url: "https://radiorecord.hostingradio.ru/djgvozd96.aacp" },
  { name: "DJ Цветкоff", url: "https://radiorecord.hostingradio.ru/tsvetkov96.aacp" },
  { name: "Dream Dance", url: "https://radiorecord.hostingradio.ru/dream96.aacp" },
  { name: "Dream Pop", url: "https://radiorecord.hostingradio.ru/dreampop96.aacp" },
  { name: "Dubstep", url: "https://radiorecord.hostingradio.ru/dub96.aacp" },
  { name: "EDM", url: "https://radiorecord.hostingradio.ru/club96.aacp" },
  { name: "EDM Classics", url: "https://radiorecord.hostingradio.ru/edmhits96.aacp" },
  { name: "Electro", url: "https://radiorecord.hostingradio.ru/elect96.aacp" },
  { name: "Eurodance", url: "https://radiorecord.hostingradio.ru/eurodance96.aacp" },
  { name: "Feel", url: "https://radiorecord.hostingradio.ru/feel96.aacp" },
  { name: "Festivals", url: "https://radiorecord.hostingradio.ru/livedjsets96.aacp" },
  { name: "Future Bass", url: "https://radiorecord.hostingradio.ru/fbass96.aacp" },
  { name: "Future House", url: "https://radiorecord.hostingradio.ru/fut96.aacp" },
  { name: "Future Rave", url: "https://radiorecord.hostingradio.ru/futurerave96.aacp" },
  { name: "GOA/PSY", url: "https://radiorecord.hostingradio.ru/goa96.aacp" },
  { name: "Groove/Tribal", url: "https://radiorecord.hostingradio.ru/groovetribal96.aacp" },
  { name: "Hard Bass", url: "https://radiorecord.hostingradio.ru/hbass96.aacp" },
  { name: "Hardstyle", url: "https://radiorecord.hostingradio.ru/teo96.aacp" },
  { name: "House Classics", url: "https://radiorecord.hostingradio.ru/houseclss96.aacp" },
  { name: "House Hits", url: "https://radiorecord.hostingradio.ru/househits96.aacp" },
  { name: "Hypnotic", url: "https://radiorecord.hostingradio.ru/hypno96.aacp" },
  { name: "Innocence", url: "https://radiorecord.hostingradio.ru/ibiza96.aacp" },
  { name: "Jungle", url: "https://radiorecord.hostingradio.ru/jungle96.aacp" },
  { name: "Lady Waks", url: "https://radiorecord.hostingradio.ru/ladywaks96.aacp" },
  { name: "Latina Dance", url: "https://radiorecord.hostingradio.ru/latina96.aacp" },
  { name: "Liquid Funk", url: "https://radiorecord.hostingradio.ru/liquidfunk96.aacp" },
  { name: "Lo-Fi", url: "https://radiorecord.hostingradio.ru/lofi96.aacp" },
  { name: "Lo-Fi House", url: "https://radiorecord.hostingradio.ru/lofihouse96.aacp" },
  { name: "Martin Garrix", url: "https://radiorecord.hostingradio.ru/martingarrix96.aacp" },
  { name: "Megamix", url: "https://radiorecord.hostingradio.ru/mix96.aacp" },
  { name: "Midtempo", url: "https://radiorecord.hostingradio.ru/mt96.aacp" },
  { name: "Minimal/Tech", url: "https://radiorecord.hostingradio.ru/mini96.aacp" },
  { name: "Moombahton", url: "https://radiorecord.hostingradio.ru/mmbt96.aacp" },
  { name: "Nejtrino & Baur", url: "https://radiorecord.hostingradio.ru/nejtrinobaur96.aacp" },
  { name: "Neurofunk", url: "https://radiorecord.hostingradio.ru/neurofunk96.aacp" },
  { name: "Nu Dance", url: "https://radiorecord.hostingradio.ru/nudance96.aacp" },
  { name: "Oliver Heldens", url: "https://radiorecord.hostingradio.ru/oliverheldens96.aacp" },
  { name: "Organic", url: "https://radiorecord.hostingradio.ru/organic96.aacp" },
  { name: "Party 24/7", url: "https://radiorecord.hostingradio.ru/party96.aacp" },
  { name: "Phonk", url: "https://radiorecord.hostingradio.ru/phonk96.aacp" },
  { name: "Pirate Station", url: "https://radiorecord.hostingradio.ru/ps96.aacp" },
  { name: "Progressive", url: "https://radiorecord.hostingradio.ru/progr96.aacp" },
  { name: "Rave FM", url: "https://radiorecord.hostingradio.ru/rave96.aacp" },
  { name: "Record", url: "https://radiorecord.hostingradio.ru/rr_main96.aacp" },
  { name: "Record 80-х", url: "https://radiorecord.hostingradio.ru/198096.aacp" },
  { name: "Record Classix", url: "https://radiorecord.hostingradio.ru/classix96.aacp" },
  { name: "Record Club Show", url: "https://radiorecord.hostingradio.ru/clubshow96.aacp" },
  { name: "Record Gold", url: "https://radiorecord.hostingradio.ru/gold96.aacp" },
  { name: "Reggae", url: "https://radiorecord.hostingradio.ru/reggae32.aacp" },
  { name: "Remix", url: "https://radiorecord.hostingradio.ru/rmx96.aacp" },
  { name: "Russian Gold", url: "https://radiorecord.hostingradio.ru/russiangold96.aacp" },
  { name: "Russian Hits", url: "https://radiorecord.hostingradio.ru/russianhits96.aacp" },
  { name: "Russian Mix", url: "https://radiorecord.hostingradio.ru/rus96.aacp" },
  { name: "Summer Dance", url: "https://radiorecord.hostingradio.ru/summerparty96.aacp" },
  { name: "Summer Lounge", url: "https://radiorecord.hostingradio.ru/summerlounge96.aacp" },
  { name: "Synthwave", url: "https://radiorecord.hostingradio.ru/synth96.aacp" },
  { name: "Tech House", url: "https://radiorecord.hostingradio.ru/techouse96.aacp" },
  { name: "Techno", url: "https://radiorecord.hostingradio.ru/techno96.aacp" },
  { name: "Technopop", url: "https://radiorecord.hostingradio.ru/technopop96.aacp" },
  { name: "Tecktonik", url: "https://radiorecord.hostingradio.ru/tecktonik96.aacp" },
  { name: "Tiesto", url: "https://radiorecord.hostingradio.ru/tiesto96.aacp" },
  { name: "TOP 100 EDM", url: "https://radiorecord.hostingradio.ru/top100edm96.aacp" },
  { name: "Trance Classics", url: "https://radiorecord.hostingradio.ru/trancehits96.aacp" },
  { name: "Trancehouse", url: "https://radiorecord.hostingradio.ru/trancehouse96.aacp" },
  { name: "Trancemission", url: "https://radiorecord.hostingradio.ru/tm96.aacp" },
  { name: "Trap", url: "https://radiorecord.hostingradio.ru/trap96.aacp" },
  { name: "Tropical", url: "https://radiorecord.hostingradio.ru/trop96.aacp" },
  { name: "UK Garage", url: "https://radiorecord.hostingradio.ru/ukgarage96.aacp" },
  { name: "Ultra Music Festival", url: "https://radiorecord.hostingradio.ru/ultra96.aacp" },
  { name: "Uplifting", url: "https://radiorecord.hostingradio.ru/uplift96.aacp" },
  { name: "VIP House", url: "https://radiorecord.hostingradio.ru/vip96.aacp" },
  { name: "Workout", url: "https://radiorecord.hostingradio.ru/workout32.aacp" },
  { name: "Веснушка FM", url: "https://radiorecord.hostingradio.ru/deti96.aacp" },  
  ];